version: '3.7'
services:
  scipy_service:
    build:
      context: .
    command: >
      uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 9111
    ports:
      - 9111:9111
    restart: always
